services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - expenses-manager-network
  expenses-manager-backend:
    container_name: expenses-manager-backend
    image: salem501/expenses-manager:1.0
    ports:
      - "8080:8080"
    networks:
      - expenses-manager-network

volumes:
  postgres:

networks:
  expenses-manager-network:
    driver: bridge
